import { avocadoAss } from "../assets";
export const mockData = [
  {
    id: 1,
    img: avocadoAss,
    productName: "Product 1",
    brand: "Brand A",
    price: 10,
    quantity: 1,
    status: "",
  },
  {
    id: 2,
    img: avocadoAss,
    productName: "Product 2",
    brand: "Brand B",
    price: 10,
    quantity: 1,
    status: "",
  },
  {
    id: 3,
    img: avocadoAss,
    productName: "Product 3",
    brand: "Brand 2",
    price: 10,
    quantity: 1,
    status: "",
  },
  {
    id: 4,
    img: avocadoAss,
    productName: "Product 4",
    brand: "Brand 4",
    price: 10,
    quantity: 1,
    status: "",
  },
  {
    id: 5,
    img: avocadoAss,
    productName: "Product 5",
    brand: "Brand 5",
    price: 10,
    quantity: 1,
    status: "",
  },
];
